### ISSUE TITLE
Scraping of Attractions Reviews is not working

### ISSUE THREAD

**Issue by piramalakia** [maxCopell/tripadvisor-scraper#32]
Hi
Running a vanilla query for scrapping attraction reviews  on a specific location gets an error of type  "Could not get reviews for attraction xyz due to session.getCookieString is not a function". 
The attractions of the location are correctly identified but the reviews are not retrieved. 

Can you please fix this?

Also hotels and restaurants reviews scrapping works perfectly
-----------
My JSON settings:
{
  "locationFullName": "Kabul",
  "locationId": "660089",
  "lastReviewDate": "2010-01-01",
  "includeRestaurants": false,
  "includeAttractions": true,
  "includeHotels": false,
  "includeReviews": true,
  "proxyConfiguration": {
    "useApifyProxy": true
  }
}
------
Log summary:
2021-05-31T09:45:07.452Z ACTOR: Pulling Docker image from repository.
2021-05-31T09:45:07.558Z ACTOR: Creating Docker container.
2021-05-31T09:45:07.656Z ACTOR: Starting Docker container.
2021-05-31T09:45:11.066Z INFO  System info {"apifyVersion":"0.20.3","apifyClientVersion":"0.6.0","osType":"Linux","nodeVersion":"v12.18.3"}
2021-05-31T09:45:11.089Z WARN  You are using an outdated version (0.20.3) of Apify SDK. We recommend you to update to the latest version (1.1.2).
.....
2021-05-31T09:45:11.133Z INFO  Input validation OK
2021-05-31T09:45:11.148Z INFO  Processing locationId: 660089
...
2021-05-31T09:45:17.125Z INFO  Found 20 attractions
2021-05-31T09:45:17.126Z INFO  Processing detail for Babur Tomb attraction
.....
2021-05-31T09:45:17.169Z INFO  Processing detail for Bibi Mahroo Hill attraction
2021-05-31T09:45:17.170Z ERROR Could not get reviews for attraction Babur Tomb due to session.getCookieString is not a function
...
2021-05-31T09:45:17.176Z ERROR Could not get reviews for attraction Bibi Mahroo Hill due to session.getCookieString is not a function
2021-05-31T09:45:17.550Z ERROR Could not process attraction... Data item at index 0 is not serializable to JSON.
2021-05-31T09:45:17.581Z Cause: Parameter "item" of type Object must be provided
2021-05-31T09:45:17.754Z INFO  BasicCrawler: All the requests from request list and/or request queue have been processed, the crawler will shut down.
2021-05-31T09:45:17.859Z INFO  Crawler final request statistics: {"avgDurationMillis":1560,"perMinute":34,"finished":1,"failed":0,"retryHistogram":[1]}
2021-05-31T09:45:17.860Z INFO  Requests failed: 0
2021-05-31T09:45:17.861Z INFO  Crawler finished.
[nZWGLC2Ua16iDl4vz (1).log](https://github.com/maxCopell/tripadvisor-scraper/files/6570227/nZWGLC2Ua16iDl4vz.1.log)

**Comment by piramalakia** [comment]
Log attached
[
[nZWGLC2Ua16iDl4vz.log](https://github.com/maxCopell/tripadvisor-scraper/files/6569568/nZWGLC2Ua16iDl4vz.log)
](url)

**Comment by pocesar** [comment]
this is fixed

**Comment by piramalakia** [comment]
Thanks but it seems the "Attractions Reviews"  it is NOT fixed yet.

Pls see attached log. 
Running the same settings:  for Restaurants/Hotels gets all the reviews but for Attractions it doesn't get any reviews. 
This new version can identify the attractions and lists the label "number of reviews" (on the previous version there was an error) but now each attraction has "0 reviews", which is false.
[KwXBK201XpeGbVo57.log](https://github.com/maxCopell/tripadvisor-scraper/files/6740203/KwXBK201XpeGbVo57.log)
Same result running Beta or Current version.
